// cArrayFormatter.mjs
// Turns an Int16Array of PCM samples into a printable/downloadable C
// source file, formatted like a firmware wave-table header.

const VALUES_PER_LINE = 16;

/**
 * Sanitize an arbitrary filename into a valid, readable C identifier.
 * e.g. "My Song #1.mp3" -> "My_Song_1"
 * @param {string} filename
 * @returns {string}
 */
export function toCIdentifier(filename) {
  const base = filename.replace(/\.[^/.]+$/, ''); // strip extension
  let id = base
    .trim()
    .replace(/[^a-zA-Z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');

  if (!id) id = 'audio';
  if (/^[0-9]/.test(id)) id = '_' + id;
  return id;
}

/**
 * Format a signed 16-bit sample as an uppercase 4-digit hex literal,
 * using its two's-complement unsigned representation (matches how
 * negative values appear in the reference wave-table example, e.g. 0x8001).
 * @param {number} sample
 */
function toHexLiteral(sample) {
  const unsigned = sample & 0xffff;
  return '0x' + unsigned.toString(16).toUpperCase().padStart(4, '0');
}

/**
 * @param {Int16Array} samples
 * @returns {string} body text, one array literal, no surrounding braces
 */
export function formatSampleBody(samples) {
  const lines = [];
  for (let i = 0; i < samples.length; i += VALUES_PER_LINE) {
    const chunk = samples.subarray(i, i + VALUES_PER_LINE);
    const isLast = i + VALUES_PER_LINE >= samples.length;
    const parts = Array.from(chunk, toHexLiteral);
    const line = isLast ? parts.join(', ') : parts.join(', ') + ',';
    lines.push('    ' + line);
  }
  return lines.join('\n');
}

/**
 * Build a full, self-contained C header for a converted sample.
 * @param {object} opts
 * @param {string} opts.identifier   Valid C identifier base name.
 * @param {string} opts.sourceName   Original filename, for the doc comment.
 * @param {Int16Array} opts.samples  Interleaved PCM (L,R,L,R,... if stereo).
 * @param {number} opts.sampleRate   Output sample rate, in Hz.
 * @param {number} opts.channels    Output channel count (1 = mono, 2 = stereo).
 * @param {object} opts.originalInfo { sampleRate, channels, duration }
 * @returns {string}
 */
export function buildHeaderFile({ identifier, sourceName, samples, sampleRate, channels, originalInfo }) {
  const guard = identifier.toUpperCase() + '_H';
  const arrayName = `${identifier}_table`;
  const lenName = `${identifier}_table_len`;
  const body = formatSampleBody(samples);

  const channelWord = channels === 1 ? 'mono' : 'stereo interleaved (L,R)';
  const frameCount = channels === 1 ? samples.length : Math.floor(samples.length / channels);
  const originalChannelWord = originalInfo.channels === 1 ? 'mono' : originalInfo.channels + '-channel';

  return `/*
 * Generated by PCM Scope from "${sourceName}"
 * Source:  ${originalInfo.sampleRate} Hz, ${originalChannelWord}, ${originalInfo.duration.toFixed(3)}s
 * Encoded: ${sampleRate} Hz, ${channelWord}, signed 16-bit PCM
 * Samples: ${samples.length}${channels > 1 ? ` (${frameCount} frames x ${channels} ch)` : ''}
 */

#ifndef ${guard}
#define ${guard}

#include <stdint.h>

const int16_t ${arrayName}[] =
{
${body}
};

const uint32_t ${lenName} = ${samples.length}u;

#endif /* ${guard} */
`;
}
